### ISSUE TITLE
Yuyuko can't properly eat files with special characters in their names

### ISSUE THREAD

**Issue by ColdNSs** [IWasAllen/Feed-Yuyuko#1]
When there are special characters in the file name, the file will not be deleted when dragged to yuyuko.
And the new file in the stomach folder will appear corrupted.

**Comment by IWasAllen** [comment]
Unfortunately, I didn't bother creating a function that encodes special symbols to be readable by the program.
But this should be fixed on the next revamp.

Thanks for reporting this issue!
